apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080      # Port sur lequel le service sera exposé
      targetPort: 8080    # Port du conteneur à rediriger
  type: NodePort        # Expose le service via un NodePort
